In [2]:
import numpy as np
import matplotlib.pyplot as plt

### 每班有10人，每人有五科，每個科目有權重

In [51]:
weights = np.array([0.25,0.25,0.25,0.15,0.10]) #權重

a = np.zeros(10)
b = np.zeros(10)
c = np.zeros(10)

for i in range(0,10):
    a[i] = np.dot(np.random.randint(0,100,5),weights) 
    b[i] = np.dot(np.random.randint(0,100,5),weights)
    c[i] = np.dot(np.random.randint(0,100,5),weights)

print(a)
print(b)
print(c)

[70.2  63.25 67.4  57.7  58.55 49.4  50.2  67.95 54.7  48.65]
[37.6  45.85 66.45 21.65 24.7  48.9  66.35 42.35 35.05 48.55]
[42.7  62.8  50.85 64.6  46.2  29.45 34.9  44.25 64.1  58.35]


In [57]:
np.array([np.mean(a),np.mean(b),np.mean(c)]) #a,b,c班的平均成績

array([58.8  , 43.745, 49.82 ])